### ISSUE TITLE
Todo: Create TMP Folder to backups

### ISSUE THREAD

**Issue by Sirherobrine23** [The-Bds-Maneger/Bds-Maneger-Core#344]
In the backups, Create temporary folder to copy files/folder, before delete temporary folder, it is cleaning code and simplify maintenance to backup server. and test git repo backup, implement don't tested.

## Todo:

- [x] Create temporary folder and Add functions to add file/folder into temp folder.
- [x] Update Zip tarball to use temporary folder.
- [x] Update git backup to use temporary folder.
- [x] More test in git repo backup.

**Comment by Sirherobrine23** [comment]
Git backup commit: c5b498e5da0762d3ca7bb7e8100eddd8ca93bb19
